experiment_id: "1"
backbone:
  provider: "openai"
  model: "o3"
scheme: "no-history"
use_vision: false
max_steps: 25
judge:
  enabled: false
initial_actions:
  - navigate:
      url: "https://www.bing.com"
      new_tab: false
system_instruction: |
  DO NOT try any actions that require log in, phone number and e-mail address.
  NOTE: ADDRESS must be set first for appropriate items to appear, most of the time.
  STOP before executing irreversible actions such as payment or reservation confirmation.

